version: "3"

services:

  api:
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - adminer
    ports:
      - "8080:8080"

  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5432:5432"
