version: "3"

services:

  api:
    restart: always
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - adminer
    ports:
      - "8080:8888"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

