version: "3"

services:

  api:
    restart: always
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin123
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - 5432:5432
    volumes:
      - 'data:/var/lib/postgresql/data'

volumes:
  data:
    driver: local
